### ISSUE TITLE
Idomatic way to fetch main interface

### ISSUE THREAD

**Issue by oppiliappan** [akashram14/BLX-Automation#3]
Write a python or shell script to:
 - get one interface with state UP 
 - not corresponding to `blx0` or `lo` loopback interface

Ideas:
 - decide "main" interface based on state, should be UP
 - decide "main" interface based on name (ethernet starts with 'e' and wireless with 'w')

**Comment by akashram14** [comment]
https://unix.stackexchange.com/questions/14961/how-to-find-out-which-interface-am-i-using-for-connecting-to-the-internet
This is basically the interface we're looking for right?

**Comment by oppiliappan** [comment]
Yeah, looks like this would work, shell script to get that interface:
```shell
route | grep 'default' | awk '{ print $8 }'
```
